[package]
name = "yutki-lp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
yutki-model = { path = "../yutki-model" }
yutki-sparse = { path = "../yutki-sparse" }
yutki-numerics = { path = "../yutki-numerics" }
yutki-gpu = { path = "../yutki-gpu" }
yutki-transform = { path = "../yutki-transform" }
yutki-runtime = { path = "../yutki-runtime" }
thiserror.workspace = true
serde.workspace = true
