[package]
name = "yutki-gpu"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
yutki-model = { path = "../yutki-model" }
yutki-sparse = { path = "../yutki-sparse" }
thiserror.workspace = true
serde.workspace = true
rayon.workspace = true

[lints]
workspace = true


